language: python
sudo: false
python:
  - 3.6
  - 3.7


cache:
  directories:
    - $HOME/.cache/pip

env:
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2


install:
  - pip install tox "coverage<=4.0"  codecov

script:
  - tox -e "d${DJANGO//.}-py${TRAVIS_PYTHON_VERSION//.}" -- py.test tests -v

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
