language: python
sudo: false
python:
  - 2.7
  - 3.6


cache:
  directories:
    - $HOME/.cache/pip

env:
  - DJANGO=1.11
  - DJANGO=2.0


matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0


install:
  - pip install tox "coverage<=4.0"  codecov

script:
  - tox -e "d${DJANGO//.}-py${TRAVIS_PYTHON_VERSION//.}" -- py.test tests -v

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
