# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 03:15
from __future__ import unicode_literals

from django.db import migrations, models

import django_regex.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regex', django_regex.fields.RegexField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DemoModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regex', django_regex.fields.RegexField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
